config = dict(
    runners=['eveworld.alternatives.physlatent.PhysicsLatentGigaWorld0Trainer'],
    project_dir='/data/datasets/gagi/giga_world_0_outputs/physlatent_gigaworld/gr1_query_adapter_warmup',
    launch=dict(
        gpu_ids=[0, 1, 2, 3, 4, 5, 6, 7],
        distributed_type='DEEPSPEED',
        deepspeed_config=dict(
            deepspeed_config_file='accelerate_configs/zero2.json',
        ),
    ),
    dataloaders=dict(
        train=dict(
            data_or_config=[
                '/data/datasets/gagi/gr1_finetune_data/packed_data',
            ],
            batch_size_per_gpu=1,
            num_workers=6,
            transform=dict(
                type='PhysLatentGigaWorld0Transform',
                num_frames=93,
                height=480,
                width=768,
                fps=16,
                random_crop=True,
                image_cfg=dict(
                    mask_generator=dict(
                        max_ref_frames=1,
                        start=1,
                        factor=4,
                    ),
                ),
            ),
            sampler=dict(
                type='DefaultSampler',
                shuffle=True,
            ),
        ),
    ),
    models=dict(
        vae_model_path='/data/datasets/gagi/giga_world_0_video_pretrain/vae',
        transformer_model_path='/data/datasets/gagi/giga_world_0_video_pretrain/transformer',
        train_mode='full',
        physics_latent=dict(
            enabled=True,
            num_tokens=8,
            prompt_dim=1024,
            latent_channels=16,
            token_dim=1024,
            hidden_dim=1024,
            num_contact_classes=4,
            num_traj_points=8,
            num_attention_heads=8,
            spatial_pool_size=(15, 24),
            dropout=0.0,
            train_backbone=False,
            loss_weights=dict(
                state=0.0,
                goal=0.0,
                contact=0.0,
                trajectory=0.0,
            ),
        ),
    ),
    optimizers=dict(
        type='CAME8Bit',
        lr=2 ** (-14.5),
    ),
    schedulers=dict(
        type='ConstantScheduler',
    ),
    train=dict(
        resume=True,
        max_steps=200,
        gradient_accumulation_steps=8,
        mixed_precision='bf16',
        checkpoint_interval=50,
        checkpoint_total_limit=5,
        checkpoint_strict=False,
        log_with='tensorboard',
        log_interval=1,
        with_ema=False,
        activation_checkpointing=True,
        activation_class_names=['TransformerBlock'],
    ),
)
